const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_MESSAGE_RECIEVED = "NEW_MESSAGE_RECIEVED";
const NEW_MESSAGE_NOTIFICATION = "NEW_MESSAGE_NOTIFICATION";
const TYPING_START = "TYPING_START";
const TYPING_STOP = "TYPING_STOP";
const NEW_REQUEST = "NEW_REQUEST";
const REFETCH_CHATS = "REFETCH_CHATS";
const ONLINEUSERS = "ONLINEUSERS";

export {
  NEW_MESSAGE,
  NEW_MESSAGE_RECIEVED,
  NEW_MESSAGE_NOTIFICATION,
  TYPING_START,
  TYPING_STOP,
  NEW_REQUEST,
  REFETCH_CHATS,
  ONLINEUSERS,
};
